services:
  - type: cron
    name: autoclaimer
    runtime: node
    schedule: "0 12 * * *"
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: PRIVATE_KEY
        sync: false
      - key: FUSE_RPC_URL
        sync: false
      - key: XDC_RPC_URL
        sync: false
      - key: MIN_GAS_BALANCE
        sync: false
